### PR TITLE
Wut

### PR DESCRIPTION
**Pull request by Lanzaa**
testing pull req.

### CODE REVIEW

**Comment by eblume** [comment]
Yup, this came in just fine. I'll let you continue doing whatever test you want to do here. :)

**Comment by Lanzaa** [comment]
This was a test of the github pull system. This was only a test. In a real pull request the comments would pertain to the diffs.

I was simply researching how to grab github pull requests from the command line. Some cool commands:

> git ls-remote
> git fetch origin '+refs/pull/*/head:refs/remotes/pull-req/*'

And a cool website:
http://www.somethingorothersoft.com/2012/05/22/pulling-github-pull-requests-with-git/

**Comment by Lanzaa** [comment]
A test of an irrelevant github feature:

> Only/_/A/small/_/test

**Comment by eblume** [comment]
Very interesting, thanks!

**Comment by Lanzaa** [comment]
nothing happened

> testing/*/world

**Comment by eblume** [comment]
Lanzaa explain yourself! :)

**Comment by Lanzaa** [comment]
First I was testing some code to grab pull-requests from command line. Then I found a bug in github and was using this issue to explain to github employee's what was wrong.

Basically the preview of a comment and the comment did not look the same.

> because of a /_/ or two /_/

When things shouldn't be crazy

> because of a /*/ or two /*/

**Comment by eblume** [comment]
Ah, very cool, thanks :)

**Pull request closed without merging**
