### PR TITLE
Added a post about StartupSJSU

### PR DESCRIPTION
**Pull request by owyongsk**
A weekend of coding and planning. Great prizes and stuff!

### CODE REVIEW

**Comment by owyongsk** [comment]
Good job on bootstrap and the git repository by the way. (:

**Comment by eblume** [comment]
At some point the CS Club will need to come up with approval process for merge requests like this. For now I'm definitely going to merge it, and thanks for the contrib!

In the future I could see people abusing this site design by publishing advertisements in such a way that it looks like the CS club is officially endorsing things that we aren't in fact officially endorsing.

I suspect the answer will be to require posts to have an 'Author' frontmatter that will be used to tag each post (eg. "Posted by: <author> <email>).

In any event, thanks again for the commit, and I will definitely try and be at the hackathon! I'll also add it to the Google Calendar, I hope that's alright with you.

**Comment by eblume** [comment]
Oh, by the way - the automatic deploy script isn't in place yet so this change won't become live until Lanzaa (Colin) gets around to it. Just FYI.

**Comment by owyongsk** [comment]
Oh, hey no problem.

But yeah, definitely there should be a process, but since you guys have to approve the merge, you can just deny it. Haha. Maybe just say all pull requests are welcome as long as there are no abuse.

**Comment by eblume** [comment]
It's a little sticky for me because I'm not a CS club officer but I've been granted permission to continue to maintain this site, at least for now.

I'm actually less concerned about the obvious 'fraud'-type abuse, because yeah, we can just not merge those requests. I'm more concerned with users of the website thinking that every post is an officially endorsed CS Club post.

Of course one way to ensure that is to in fact say that every post (and I am using "post" to specifically refer to Jekyll posts, ie. anything in the _posts directory, like this is) must in fact be vetted and endorsed by the CS Club officership.

Personally I would prefer that we keep it much more open than that and simply insert disclaimers in to the template that posts don't necessarily reflect the views of the CS club.

I'll submit a patch later on that does that.

Hey, I'm curious - I wasn't expecting a post like this to be added so quickly after the launch. Are you used to Jekyll already or did you figure it out on your own in the few hours between launch and this post?

Either way, how did you like the setup? Was it intuitive? Was there any lacking documentation?

**Comment by owyongsk** [comment]
I've been playing with Ruby on Rails in the past 7 months, so I have Ruby and my whole environment set up. Only heard of Jekyll as of 1 hour ago. Decided to check it out. Found out that it's based on Ruby and loves Markdown, which I like both.

So yeap, the gem install part was intuitive for me as I played with Ruby. And the whole posts are added once the file is saved in the directory is pretty cool. But yeah.

Anyways, you should come to that event that I just posted. Haha.

**Pull request merged**
