### PR TITLE
Any thoughts on this?

### PR DESCRIPTION
**Pull request by JPAdv-zz**
I have made some changes to the website. Any feedback would be greatly appreciated. Thanks.

### CODE REVIEW

**Comment by eblume** [comment]
I'm a big fan of moving this away from the default bootstrap theme, but I can't help feel like this is a very familiar design as well. Is this design inspired by something, perhaps?

In any case, heartily approved. Thanks for the contributions!

**Comment by JPAdv-zz** [comment]
As you might have noticed, it is not a big update. I only modified what was already there and improved a few things (if you can call these improvements). So basically it is using bootstrap. I also agree that the site can be switched from bootstrap to a complete different looking one. I will see if I can pull something off and will ask a pull request sometime in the future.

**Comment by eblume** [comment]
Oh I meant that it looks visually less like a bootstrap page now, which is nice. Before it was very close to stock bootstrap. I don't mind the overall bootstrap framework, I just felt the old coloration and style was a bit 'lazy' as it was very close to default bootstrap.

But I'm really curious about the colors, it seems _very_ familiar. Any chance it's something you might remember?

**Comment by JPAdv-zz** [comment]
I now understand what you meant about moving the default bootstrap away. In relation to the colors, I think it kind of resembles university's colors? Unless, it is something for which I cannot remember.

**Pull request merged**
